[package]
name = "image-packer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fatfs = "0.3.6"
gpt = { version = "3.1.0" }